services:

  mongodb:
    image: mongo:4
    expose:
      - "27017"
    ports:
      - "27017:27017"

  redis:
    image: redis:3
    expose:
      - "6379"
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"

  superdesk-server:
    build: ./server
    depends_on:
      - redis
      - mongodb
      - elastic
    environment:
      - SUPERDESK_URL=http://superdesk.local:8080/api
      - DEMO_DATA=1 # install demo data, set to 0 if you want clean install
      - WEB_CONCURRENCY=2
      - SUPERDESK_CLIENT_URL=http://superdesk.local:8080
      - CONTENTAPI_URL=http://superdesk.local:8080/capi
      - MONGO_URI=mongodb://mongodb/superdesk
      - CONTENTAPI_MONGO_URI=mongodb://mongodb/superdesk_capi
      - PUBLICAPI_MONGO_URI=mongodb://mongodb/superdesk_papi
      - LEGAL_ARCHIVE_URI=mongodb://mongodb/superdesk_legal
      - ARCHIVED_URI=mongodb://mongodb/superdesk_archive
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_INDEX=superdesk
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - DEFAULT_TIMEZONE=Europe/Prague
      - SECRET_KEY=secretkey
      # More configuration options can be found at https://superdesk.readthedocs.io/en/latest/settings.html

  superdesk-client:
    build: ./client
    environment:
      # If not hosting on localhost, change these lines
      - SUPERDESK_URL=http://superdesk.local:8080/api
      - SUPERDESK_WS_URL=ws://superdesk.local:8080/ws
      - IFRAMELY_KEY
    depends_on:
      - superdesk-server
    ports:
      - "8080:80"
    networks:
      default:
        aliases:
          - superdesk.local


networks:
    default:
      external:
        name: sp-publisher-network
